[package]
name = "rsinit"
version = "0.1.0"
authors = ["LeeSmet <lee.smet@hotmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
pretty_env_logger = "0.3"

[lib]
name = "librsinit"
path = "src/lib.rs"

[[bin]]
name = "rsinit"
path = "src/main.rs"
